version: "3.8"
# networks:
  # frontend:
  # backend:
volumes:
  php-socket:
  db-store:
services:
  nginx:
    image: ${SERVICE_NAME}:nginx
    container_name: ${SERVICE_NAME}_nginx
    build:
      context: ./docker/nginx
      args:
        - DIST_DIR=${DIST_DIR}
    volumes:
      - php-socket:/var/run/php-fpm
      - ${MOUNT_DIR}:/var/www/${DIST_DIR}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    # depends_on:
    #   - php-fpm
    # networks:
    #   - backend

  php-fpm:
    image: ${SERVICE_NAME}:php-fpm
    container_name: ${SERVICE_NAME}_php-fpm
    build:
      context: ./docker/php-fpm
      args:
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
        - DIST_DIR=${DIST_DIR}
    volumes:
      - php-socket:/var/run/php-fpm
      - ${MOUNT_DIR}:/var/www/${DIST_DIR}
    # networks:
    #   - backend

  mysql:
    image: ${SERVICE_NAME}:mysql
    container_name: ${SERVICE_NAME}_mysql
    build: ./docker/mysql
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # networks:
    #   - backend

  postgres:
    image: ${SERVICE_NAME}:postgres
    container_name: ${SERVICE_NAME}_postgres
    build: ./docker/postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # networks:
    #   - backend